services:
  currency_app:
    container_name: cur_app_cont
    environment:
      - VERSION=${VERSION}
      - PORT=${PORT}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    restart: always
