services:
  currency_app:
    container_name: cur_app_cont
    environment:
      - VERSION=0.1.6
      - PORT=8000
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
