---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update-cache: true

- name: Download k8s package repos gpg-key.
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add k8s repo
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /'
    state: present
    filename: k8s_utils
    update_cache: true

- name: Ensure kubelet and kubeadm are installed
  ansible.builtin.apt:
    name: "{{ kubernetes_packages }}"
    state: present
    update_cache: true

- name: Add Kubernetes apt preferences file to pin a version
  ansible.builtin.template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
    mode: '0644'
