---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
  labels:
    app.kubernetes.io/name: test-release
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: test-release
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: currency-app
  labels:
    app.kubernetes.io/name: test-release
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-release
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-release
    spec:
      containers:
        - name: currency-app
          image: m0kes/yadro:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 192Mi
          ports:
            - containerPort: 8000
          env:
            - name: HOST
              value: 0.0.0.0
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: currency-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: currency-service
            port:
              number: 8000